### ISSUE TITLE
Randomly fail to apply prepatch, and the game stuck at loading screen

### ISSUE THREAD

**Issue by masakitenchi** [bbradson/Performance-Fish#12]
Sorry for being not able to provide any log since this happens during startup, but comparing these 3 log screenshot, I think there are some soft incompatibility between prepatcher and fish:
![image](https://github.com/bbradson/Performance-Fish/assets/11086210/0cee4dec-814f-432e-9c85-1c8df176d510)
![image](https://github.com/bbradson/Performance-Fish/assets/11086210/59189633-af7f-470c-9a89-bd02133b27ba)
![image](https://github.com/bbradson/Performance-Fish/assets/11086210/de4c8742-a0dc-48ce-9c9f-c41db85fb2b2)

First pic is when it gets stuck (and had to alt+f4 to force shut the game down), second is when it successfully applying prepatches, third is without fish

Please contact me if you need more information

**Comment by bbradson** [comment]
The Enlighten thing is a unity feature and not relevant to anything mods are doing: https://docs.unity3d.com/Manual/realtime-gi-using-enlighten.html  
Loading getting stuck happened a total of 2 times for me since I've started working with Prepatcher as dependency months ago, so I don't really have a way to verify whether anything I change would impact this or not. The commit I pushed just now includes a tiny change that may have some relevance though. If this keeps happening or you even have a way to reproduce it somewhat consistently, please let me know.

**Comment by masakitenchi** [comment]
Thanks. I may reopen this once it happens again and I could find a way to reproduce the loading issue
