### ISSUE TITLE
Error when creating stockpiles while the mod is active

### ISSUE THREAD

**Issue by stachonix** [bbradson/Performance-Fish#28]
The situation is similar to a previous issue, and after reading it, I checked if I wasn't missing any dependencies, which doesn't seems to be the case. The error happens once and then doesn't happen again when creating stockpiles. I suspect it may be somewhat related to Allow Zones mod, as when I had it active, no stockpile would be creatable. I hope this information proves to be useful for troubleshooting.

Hugslib trace: https://gist.github.com/HugsLibRecordKeeper/b6010a79b4327d078e535a00b3c0561a

**Comment by bbradson** [comment]
Good morning. That log contains so many errors that it stopped logging before even finishing loading into a save, see line 7463. Many of those could be caused by removal of mods that are not safe to remove mid-game, but there's no way to tell from my side.
It has mods throwing about failing to reference stats that were removed in the 1.1 version of rimworld, like tailoring speed, smithing speed and sculpting speed at lines 3772 to 3778. The vanilla RotStink thought appears to be somehow missing, see line 3120 for example. The vanilla blunt tool capacity def is somehow missing too. Completely redownloading rimworld might fix that, or it could be caused by outdated mods, which threw the stat reference errors too, overwriting contents and removing those defs in the process.
In order to fix any bugs with Performance Fish I'd need to be able to reproduce them with a minimal modlist. It is not possible to fix something that requires several hundreds of other errors to be thrown first, as those kinds of errors often entirely prevent other necessary code from running

**Comment by bbradson** [comment]
Error handling for issues in stats from other mods has been added now
