### ISSUE TITLE
Is there a plan for compatibility with 1.5?

### ISSUE THREAD

**Issue by NightmareZero** [bbradson/Performance-Fish#32]
There are too many subscribed mods, it will be very laggy without fish

**Comment by 32bitx64bit** [comment]
I mean. If you would like to do a pull request and get 1.5 running. Be my guest. Otherwise give the dev some damn time bruh.

1.5 just was announced. And modders are still working on it.

It'll be especially hard for performance mods sense 1.5 has some multi threading now. In the pawn rendering system.

**Comment by USMP-lancer** [comment]
im not exactly the dev but i think i got an idea of his plan
first hes probably making sure performance fishes lib fishery works
then he will begin porting performance fish to 1.5
im not the dev so take that all with a grain of salt, i just know hes working on the lib and not this(from what i can see, a dev can always have a secret local branch)
