### ISSUE TITLE
is there any plan to fix compatibility with rimmsqol ?

### ISSUE THREAD

**Issue by NightmareZero** [bbradson/Performance-Fish#6]
Incompatibilities:

Performance Fish: Users have reported loss of user settings(especially stat entries). Does not affect everyone, use at your own risk.

**Comment by bbradson** [comment]
This incompatibility was declared from Rimmsqol's side. The mods work together on my end and seem to work for everyone else I've asked too, so there's just absolutely nothing I could possibly do here. The Rimmsqol author doesn't even seem to know himself how to trigger the bug

**Comment by TurtleShroom** [comment]
I can confirm that I have encountered this bug.

Apparently, when I close RIMMSQOL or make any edits, or load a new game, it corrupts my RIMMSQOL file and causes multiple Materials and Buildings to randomly change ALL Statistic Multipliers to a factor of one thousand eight hundred. I thankfully had a back up to restore from, but I am afraid that this corruption will randomly hit again when I load a new saved game.

**Comment by quicksilverfox** [comment]
From rimmsqol mod description:

Performance Fish: Sufficently large configuration files will start discarding changes. Users must deactivate the invoke reflection cache in PF's mod settings.

**Comment by bbradson** [comment]
Yes, I don't know what a "sufficiently large configuration file" is meant to be. The bug doesn't trigger on my end. I would at the very least need a log with a minimal mod list and the error inside, as well as proper reproduction steps I can actually follow without spending literal days trying to get some unknown feature to break in that mod's menu.

**Comment by bbradson** [comment]
I did manage to reproduce the issue after a bit of back and forth on Discord, but a proper fix turned out to not be all that simple to implement. As a workaround, the ReflectionCaching:Invoke setting is now disabled by default. RIMMSqol should now correctly function alongside fish, as long as fish's settings aren't modified.

**Comment by TurtleShroom** [comment]
Fantastic. Thank you for letting me know.


(E-Mail reply)
------
Jesus Loves You and Died for You!

     On Saturday, June 3, 2023 at 02:29:49 PM EDT, bbradson ***@***.***> wrote:  
 
 


I did manage to reproduce the issue after a bit of back and forth on Discord, but a proper fix turned out to not be all that simple to implement. As a workaround, the ReflectionCaching:Invoke setting is now disabled by default. RIMMSqol should now correctly function alongside fish, as long as fish's settings aren't modified.

**Comment by NightmareZero** [comment]
.
